blank_issues_enabled: false
contact_links:
  - name: NASPlus
    url: https://github.com/NASPlus/NASPlus/
    about: NASPlus
  - name: NASPlus
    url: https://github.com/NASPlus/NASPlus/
    about: NASPlus
